export const DEFAULT_HEADER_FONT = 'DEFAULT_HEADER_FONT';
export const CONFIG = {
  DEFAULT_HEADER_FONT: 'DOS Rebel',
  OUTPUT_HEADER_FONT: 'DOS Rebel',
};
export const SCREEN_TITLE = 'SCREEN_TITLE';
