import { LibraryModule, RegisterCache } from '@automagical/boilerplate';
import { DiscoveryModule } from '@nestjs/core';

import { LIB_TTY } from '../config';
import {
  AcknowledgeComponentService,
  ApplicationManagerService,
  BooleanEditorService,
  ChartingService,
  ColorsService,
  ComparisonToolsService,
  ComponentExplorerService,
  ConfigBuilderService,
  ConfirmEditorService,
  DateEditorService,
  DiscriminatorEditorService,
  EditorExplorerService,
  EnumEditorService,
  EnvironmentService,
  FooterEditorService,
  GitService,
  KeyboardManagerService,
  KeymapService,
  ListBuilderComponentService,
  MainCLIService,
  MenuComponentService,
  NumberEditorService,
  PinnedItemService,
  PromptService,
  ReplExplorerService,
  ScreenService,
  StackService,
  StringEditorService,
  SystemService,
  TableBuilderComponentService,
  TableService,
  TextRenderingService,
  ThemeService,
} from '../services';
import { LayoutManagerService } from '../services/meta/layout-manager.service';

@LibraryModule({
  exports: [
    ApplicationManagerService,
    ChartingService,
    ColorsService,
    ComparisonToolsService,
    ConfigBuilderService,
    EnvironmentService,
    LayoutManagerService,
    GitService,
    KeymapService,
    PinnedItemService,
    PromptService,
    ScreenService,
    StackService,
    SystemService,
    TableService,
    TextRenderingService,
  ],
  imports: [DiscoveryModule, RegisterCache()],
  library: LIB_TTY,
  providers: [
    AcknowledgeComponentService,
    ApplicationManagerService,
    BooleanEditorService,
    ChartingService,
    ColorsService,
    ComparisonToolsService,
    ComponentExplorerService,
    ConfigBuilderService,
    ConfirmEditorService,
    DateEditorService,
    DiscriminatorEditorService,
    EditorExplorerService,
    EnumEditorService,
    EnvironmentService,
    FooterEditorService,
    GitService,
    KeyboardManagerService,
    KeymapService,
    LayoutManagerService,
    ListBuilderComponentService,
    MainCLIService,
    MenuComponentService,
    NumberEditorService,
    PinnedItemService,
    PromptService,
    ReplExplorerService,
    ScreenService,
    StackService,
    StringEditorService,
    SystemService,
    TableBuilderComponentService,
    TableService,
    TextRenderingService,
    ThemeService,
  ],
})
export class MainCLIModule {}
