import { ApplicationModule } from '@steggy/boilerplate';
import { TTYModule } from '@steggy/tty';

import {
  ADMIN_KEY,
  APP_TITLE,
  CONFIG_SCANNER,
  CONTROLLER_API,
  MAX_GRAPH_WIDTH,
  REFRESH_SLEEP,
  USER_ID,
} from '../config';
import {
  BaseDomainService,
  ClimateService,
  DebugService,
  DeviceService,
  EntityHistoryService,
  EntityService,
  FanGroupCommandService,
  FanService,
  GroupActionService,
  GroupCommandService,
  GroupStateService,
  HomeFetchService,
  KunamiBuilderService,
  LightGroupCommandService,
  LightService,
  LockGroupCommandService,
  LockService,
  MainCLIService,
  MediaService,
  MetadataService,
  PersonCommandService,
  PersonStateService,
  PinnedItemService,
  RoomCommandService,
  RoomStateService,
  RoutineActivateService,
  RoutineCommandBuilderService,
  RoutineCommandService,
  RoutineService,
  ScheduleBuilderService,
  ServerControlService,
  ServerLogsService,
  SolarBuilderService,
  StateChangeBuilderService,
  SwitchGroupCommandService,
  SwitchService,
} from '../services';

@ApplicationModule({
  application: Symbol('home-cli'),
  configuration: {
    [ADMIN_KEY]: {
      description: 'Admin key for the home controller',
      required: true,
      type: 'string',
    },
    [APP_TITLE]: {
      default: 'Home CLI',
      description: 'Header text for when the script first starts',
      type: 'string',
    },
    [CONFIG_SCANNER]: {
      default: false,
      description:
        'Scan and output the configuration instead of running the CLI',
      type: 'boolean',
    },
    [CONTROLLER_API]: {
      default: 'http://dev-controller.localhost',
      description: 'API endpoint',
      type: 'string',
    },
    [MAX_GRAPH_WIDTH]: {
      description: 'Used with ascii charts',
      type: 'number',
    },
    [REFRESH_SLEEP]: {
      default: 100,
      description:
        'Pause time after issuing commands before refreshing state information',
      type: 'number',
    },
    [USER_ID]: {
      description: 'Person ID to pull pinned information from',
      type: 'string',
    },
  },
  imports: [TTYModule],
  providers: [
    BaseDomainService,
    ClimateService,
    DebugService,
    DeviceService,
    EntityHistoryService,
    EntityService,
    FanGroupCommandService,
    FanService,
    GroupActionService,
    GroupCommandService,
    GroupStateService,
    HomeFetchService,
    KunamiBuilderService,
    LightGroupCommandService,
    LightService,
    LockGroupCommandService,
    LockService,
    MainCLIService,
    MediaService,
    MetadataService,
    PersonCommandService,
    PersonStateService,
    PinnedItemService,
    RoomCommandService,
    RoomStateService,
    RoutineActivateService,
    RoutineCommandBuilderService,
    RoutineCommandService,
    RoutineService,
    ScheduleBuilderService,
    ServerControlService,
    ServerLogsService,
    SolarBuilderService,
    StateChangeBuilderService,
    SwitchGroupCommandService,
    SwitchService,
  ],
})
export class HomeCLIModule {}
