import { TransformObjectId } from '@automagical/persistence';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Expose, Type } from 'class-transformer';
import {
  IsDateString,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';
import { Document } from 'mongoose';

import { RoomSaveStateDTO, RoomSensorDTO } from '../rooms';

/**
 * Entity types describe the capability / expectations of the entity as it relates to the controller logic
 *
 * These are not meant to be a subsitute for home assistant domain,
 * but a way of reducing the total number of operations a room can perform.
 * Also describes the information that needs to get persisted in save states
 */
export enum ROOM_ENTITY_TYPES {
  /**
   * Normal entities support turnOn / turnOff commands.
   * Does not imply anything about how turned on it is though (fans may turn on at 100%)
   *
   * Examples:
   *
   *  - media player
   *  - light
   *  - switch
   *  - fan
   */
  normal = 'normal',
  /**
   * Accessories turn on in response to custom logic, and specially flagged turnOn commands
   *
   * Turn off as normal with an turn off command
   */
  accessory = 'accessory',
  /**
   * Forward the same command to groups (if possible)
   */
  groups = 'groups',
}

export class RoomEntityDTO {
  entity_id: string;
  type: ROOM_ENTITY_TYPES;
}

@Schema({
  collection: `room`,
  timestamps: {
    createdAt: 'created',
    updatedAt: 'modified',
  },
})
export class RoomDTO {
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsString()
  @TransformObjectId()
  public _id?: string;
  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;
  @IsNumber()
  @IsOptional()
  @Prop({ default: null, type: 'number' })
  public deleted?: number;

  @Type(() => RoomEntityDTO)
  @Expose()
  @Prop()
  @ValidateNested()
  public entities?: RoomEntityDTO[];

  @IsString()
  @Prop({ required: true, type: 'string' })
  @Expose()
  public friendlyName: string;

  /**
   * Reference to group entries. References the `name` attribute of the group
   */
  @IsOptional()
  @Prop({
    type: [String],
  })
  @IsString({ each: true })
  @Expose()
  public groups?: string[];
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;

  @Prop()
  @Expose()
  @IsOptional()
  @Type(() => RoomSaveStateDTO)
  @ValidateNested({ each: true })
  public save_states?: RoomSaveStateDTO[];

  @Prop()
  @Expose()
  @IsOptional()
  @Type(() => RoomSensorDTO)
  @ValidateNested({ each: true })
  public sensors?: RoomSensorDTO[];
}

export type RoomDocument = RoomDTO & Document;
export const RoomSchema = SchemaFactory.createForClass(RoomDTO);
