import { TransformObjectId } from '@automagical/persistence';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Expose } from 'class-transformer';
import {
  IsDateString,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';
import { Document } from 'mongoose';

import { FanCacheDTO, LightingCacheDTO } from '../dto';
import { RoutineActivateDTO } from '../routines';

export class RoomEntitySaveStateDTO<EXTRA = LightingCacheDTO | FanCacheDTO> {
  public entity_id: string;
  public extra?: EXTRA;
  public state: string;
}
export enum ROUTINE_TYPE {
  state_change = 'state_change',
  // schedule = 'schedule',
}

@Schema({
  collection: `save_state`,
  timestamps: {
    createdAt: 'created',
    updatedAt: 'updated',
  },
})
export class RoutineDTO {
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsString()
  @TransformObjectId()
  public _id?: string;

  @IsOptional()
  @ValidateNested({ each: true })
  @Prop()
  public activate?: RoutineActivateDTO[];

  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;

  @IsNumber()
  @IsOptional()
  @Prop({ default: null, type: 'number' })
  public deleted?: number;

  @ValidateNested()
  @IsOptional()
  @Prop()
  /**
   * Describe the state of every active entity
   */
  public entities?: RoomEntitySaveStateDTO[];

  @IsString()
  @Prop({ required: true, type: 'string' })
  @Expose()
  public friendlyName: string;

  /**
   * How the groups should react.
   * Must be a valid action for the group, or a valid state id for the group
   */
  public groups?: Record<string, 'turnOn' | 'turnOff' | string>;

  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;
}

export type RountineDocument = RoutineDTO & Document;
export const RoutineSchema = SchemaFactory.createForClass(RoutineDTO);
