---
version: '2'

volumes:
  mongo:

services:
  home-controller:
    image: ghcr.io/ccontour/home-controller:latest
    container_name: home-controller
  volumes:
    # Sync the server time with the container time
    - /usr/share/zoneinfo/US/Central:/etc/localtime
    - /etc/timezone:/etc/timezone
    # Configuration
    - /path/to/your-config:/user/node/.config/home-controller
  restart: unless-stopped
  ports:
    - 7000:7000

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo:/data/db
