---
version: "2.1"

services:
  home-controller:
    image: automagical/home-controller:latest
    container_name: home-controller
    volumes:
      # Sync the server time with the container time
      - /usr/share/zoneinfo/US/Central:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - 10319:3000
    environment:
      - MQTT_HOST=10.0.0.33
      - MQTT_PORT=1883
      - DEBUG=*,-avvio,-mqtt-packet*,-express*

      # Make sure to set this, or nodejs picks the wrong TZ
      # Value should be associated with the /usr/share/zoneinfo from above
      - TZ=US/Central

      # Near Austin, TX
      # Used with solar position calculations.
      # As precise as you want, used for calculating golden hour / sunset / etc times
      - LAT=30.2672
      - LONG=-97.7431

  redis:
    container_name: home-controller_redis
    image: redis
    volumes:
      - /mnt/tier_1/automagical/home-controller/redis:/data
    restart: unless-stopped
