export const CIRCADIAN_MAX_TEMP = 'CIRCADIAN_MAX_TEMP';
export const CIRCADIAN_MIN_TEMP = 'CIRCADIAN_MIN_TEMP';
export const MIN_BRIGHTNESS = 'MIN_BRIGHTNESS';
export const SECRETS = 'SECRETS';
export const SAFE_MODE = 'SAFE_MODE';
export const SEQUENCE_TIMEOUT = 'SEQUENCE_TIMEOUT';
export const RECENT_ROUTINE_TTL = 'RECENT_ROUTINE_TTL';
