import { Prop } from '@nestjs/mongoose';
import { IsDateString, IsNumber, IsOptional, IsString } from 'class-validator';
import { Schema as MongooseSchema } from 'mongoose';

import { TransformObjectId } from './transform-object-id.decorator';

/**
 * Common properties between all objects
 */
export abstract class BaseDTO {
  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;
  @IsNumber()
  @IsOptional()
  @Prop({ default: null })
  public deleted?: number;
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;
  /**
   * User ID for owner of this entity
   *
   * See Users collection in Portal Base
   */
  @IsString()
  @IsOptional()
  @Prop({ index: true })
  @TransformObjectId()
  public owner?: string;
  /**
   * If defined, then this must be a stage. ID reference to another project
   */
  @IsOptional()
  @IsString()
  @Prop({
    default: null,
    index: true,
    ref: 'project',
    required: true,
    type: MongooseSchema.Types.ObjectId,
  })
  @TransformObjectId()
  public project?: string;
}
