import { Prop, Schema } from '@nestjs/mongoose';
import { ApiProperty } from '@nestjs/swagger';
import { TransformObjectId } from '@steggy/utilities';
import {
  IsDateString,
  IsNumber,
  IsOptional,
  IsString,
  MinLength,
  ValidateNested,
} from 'class-validator';

import { MINIMUM_NAME_SIZE } from '../constants';

export class CodeEnableDTO {
  public type?: 'enable' | 'disable';
}

@Schema({
  collection: 'code',
  timestamps: {
    createdAt: 'created',
    updatedAt: 'modified',
  },
})
export class CodeDTO {
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsString()
  @ApiProperty({ required: false })
  @TransformObjectId()
  public _id?: string;

  @IsString()
  @Prop()
  @ApiProperty()
  public code: string;

  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @ApiProperty({ required: false })
  @IsDateString()
  @Prop({ index: true })
  public created?: Date;

  @IsNumber()
  @ApiProperty({ required: false })
  @IsOptional()
  @Prop({ default: null, index: true, type: 'number' })
  public deleted?: number;

  @ValidateNested()
  @IsOptional()
  @ApiProperty({ required: false, type: [CodeEnableDTO] })
  @Prop({ index: true })
  public enable?: CodeEnableDTO;

  @IsString()
  @Prop({ required: true, type: 'string' })
  @ApiProperty()
  @MinLength(MINIMUM_NAME_SIZE)
  public friendlyName: string;

  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @ApiProperty({ required: false })
  @IsDateString()
  @Prop({ index: true })
  public modified?: Date;

  @IsString()
  @Prop()
  @ApiProperty()
  @IsOptional()
  public source?: string;
}
