# docker compose -f ./databases.docker-compose.yaml up -d
# docker-compose -f ./databases.docker-compose.yaml up -d
---
version: '2.2'

volumes:
  mongo:

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
