---
version: "2.1"

volumes:
  mongo:

services:
  home-controller:
    image: mp3three/home-controller:latest
    container_name: home-controller
    volumes:
      # Configuration
      - /path/to/config:/.home-controllerrc
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    ports:
      - 7000:7000

  redis:
    container_name: home-controller_redis
    image: redis
    restart: unless-stopped

  mongo:
    container_name: home-controller_mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
