---
version: "2.1"

services:
  home-controller:
    image: ghcr.io/ccontour/home-controller:latest
    container_name: home-controller
    volumes:
      # Sync the server time with the container time
      - /usr/share/zoneinfo/US/Central:/etc/localtime
      - /etc/timezone:/etc/timezone
      # Configuration
      - /root/.config:/user/node/.config
    restart: unless-stopped
    # depends_on:
      # - redis
    ports:
      - 7009:3000

  # redis:
  #   container_name: home-controller_redis
  #   image: redis
  #   restart: unless-stopped
