/**
 * Includes emoji and a spacing spacer space... space
 */
export const ICONS = {
  ACTIVATE: '🏁 ',
  CAPTURE: '📸 ',
  COMMAND: '🎼 ',
  CONFIGURE: '⚙ ',
  COPY: '📋 ',
  CREATE: '➕ ',
  DEBUG: '🐜 ',
  DELETE: '🚫 ',
  DESCRIBE: '🔬 ',
  DESTRUCTIVE: '🚨 ',
  DEVICE: '📟 ',
  DONE: '🗿 ',
  DOWN: '⏬ ',
  EDIT: '✏ ',
  ENTITIES: '🗃 ',
  EVENT: '🎆 ',
  GROUPS: '🎳 ',
  GUIDED: '🚌 ',
  LINK: '🔗 ',
  MANUAL: '🔨 ',
  NAME: '💭 ',
  RENAME: '✏ ',
  ROOMS: '🏡 ',
  ROUTINE: '🛰 ',
  SAVE: '💾 ',
  STATE_MANAGER: '🖼 ',
  TOGGLE_OFF: '📪 ',
  TOGGLE_ON: '📫 ',
  TURN_OFF: '🌝 ',
  TURN_ON: '🌞 ',
  UP: '⏫ ',
  WARNING: '🚧 ',
};
