/**
 * Includes emoji and a spacing spacer space... space
 */
export const ICONS = {
  ACTIVATE: '🏁 ',
  ANIMATION: '📽 ',
  BACK: '🔙 ',
  BRIGHTNESS: '💡 ',
  CAPTURE: '📸 ',
  CIRCADIAN: '🕯 ',
  COLOR: '🏮 ',
  COMMAND: '🎼 ',
  CONFIGURE: '⚙ ',
  COPY: '📋 ',
  CREATE: '➕ ',
  DEBUG: '🐜 ',
  DELETE: '🚫 ',
  DESCRIBE: '🔬 ',
  DESTRUCTIVE: '🚨 ',
  DEVICE: '📟 ',
  DONE: '🗿 ',
  DOWN: '📉 ',
  EDIT: '✏ ',
  ENTITIES: '🗃 ',
  EVENT: '🎆 ',
  GROUPS: '🎳 ',
  GUIDED: '🚌 ',
  HISTORY: '🕵 ',
  LINK: '🔗 ',
  MANUAL: '🔨 ',
  NAME: '💭 ',
  PIN: '📌 ',
  RENAME: '✏ ',
  ROOMS: '🏡 ',
  ROUTINE: '🛰 ',
  SAVE: '💾 ',
  STATE_MANAGER: '🖼 ',
  SWAP: '🔁 ',
  TOGGLE_OFF: '📪 ',
  TOGGLE_ON: '📫 ',
  TURN_OFF: '🌑 ',
  TURN_ON: '🌞 ',
  UP: '📈 ',
  WARNING: '🚧 ',
};
