import { DBFake } from '@automagical/contracts';
import { Prop } from '@nestjs/mongoose';
import { IsDateString, IsNumber, IsOptional, IsString } from 'class-validator';
import dayjs from 'dayjs';
import { Schema as MongooseSchema } from 'mongoose';

import { BaseOmitProperties } from '.';
import { TransformObjectId } from './transform-object-id.decorator';

/**
 * Common properties between all objects
 */
export abstract class BaseDTO extends DBFake {
  // #region Public Static Methods

  public static fake(): Omit<BaseDTO, BaseOmitProperties> {
    return {
      ...super.fake(),
      created: dayjs().toDate(),
      modified: dayjs().toDate(),
    };
  }

  // #endregion Public Static Methods

  // #region Object Properties

  @IsNumber()
  @IsOptional()
  @Prop({ default: null })
  public deleted?: number;
  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;
  /**
   * If defined, then this must be a stage. ID reference to another project
   */
  @IsOptional()
  @IsString()
  @Prop({
    default: null,
    index: true,
    ref: 'project',
    required: true,
    type: MongooseSchema.Types.ObjectId,
  })
  @TransformObjectId()
  public project?: string;
  /**
   * User ID for owner of this entity
   *
   * See Users collection in Portal Base
   */
  @IsString()
  @IsOptional()
  @Prop({ index: true })
  @TransformObjectId()
  public owner?: string;

  // #endregion Object Properties
}
