export const PROJECT_PERSISTENCE_DRIVER = Symbol('PROJECT_PERSISTENCE_DRIVER');
export const ACCESS_PERSISTENCE_DRIVER = Symbol('ACCESS_PERSISTENCE_DRIVER');
export const ACTION_ITEM_PERSISTENCE_DRIVER = Symbol(
  'ACTION_ITEM_PERSISTENCE_DRIVER',
);
export const ACTION_PERSISTENCE_DRIVER = Symbol('ACTION_PERSISTENCE_DRIVER');
export const FORM_PERSISTENCE_DRIVER = Symbol('FORM_PERSISTENCE_DRIVER');
export const PERMISSION_PERSISTENCE_DRIVER = Symbol(
  'PERMISSION_PERSISTENCE_DRIVER',
);
export const ROLE_PERSISTENCE_DRIVER = Symbol('ROLE_PERSISTENCE_DRIVER');
export const SESSION_PERSISTENCE_DRIVER = Symbol('SESSION_PERSISTENCE_DRIVER');
export const SUBMISSION_PERSISTENCE_DRIVER = Symbol(
  'SUBMISSION_PERSISTENCE_DRIVER',
);
export const TAG_PERSISTENCE_DRIVER = Symbol('TAG_PERSISTENCE_DRIVER');
export const TOKEN_PERSISTENCE_DRIVER = Symbol('TOKEN_PERSISTENCE_DRIVER');

export const MONGOOSE = Symbol('MONGOOSE');
export * from './mongo';
