export const ALL_ENTITIES_UPDATED = 'ALL_ENTITIES_UPDATED';
export const CONNECTION_RESET = 'CONNECTION_RESET';
export const HA_RAW_EVENT = 'raw-event';
export const HA_EVENT_STATE_CHANGE = 'HA_EVENT_STATE_CHANGE';
export const HA_SOCKET_READY = 'HA_SOCKET_READY';
export const GLOBAL_ON = 'GLOBAL_ON';
export const GLOBAL_OFF = 'GLOBAL_OFF';
