export const ALL_ENTITIES_UPDATED = 'ALL_ENTITIES_UPDATED';
export const CONNECTION_RESET = 'CONNECTION_RESET';
export const HA_EVENT_STATE_CHANGE = 'HA_EVENT_STATE_CHANGE';
export const HA_SOCKET_READY = 'HA_SOCKET_READY';
