export const CIRCADIAN_UPDATE = 'CIRCADIAN_UPDATE';
export const LIGHT_FORCE_CIRCADIAN = 'LIGHT_FORCE_CIRCADIAN';
export const IGNORE_ENTITY = 'IGNORE_ENTITY';
export const DEBUG_LOG = 'DEBUG_LOG';
export const MINIMUM_NAME_SIZE = 2;
