export const HEADER_COLOR = 'HEADER_COLOR';
export const PINNED_ITEMS = 'PINNED_ITEMS';
export const PAGE_SIZE = 'PAGE_SIZE';

export const BACKGROUND_MENU = 'BACKGROUND_MENU';
export const BORDER_COLOR_ACTIVE = 'BORDER_COLOR_ACTIVE';
export const BORDER_COLOR_INACTIVE = 'BORDER_COLOR_INACTIVE';
export const BORDER_COLOR_WARN = 'BORDER_COLOR_WARN';
export const BORDER_COLOR_ERROR = 'BORDER_COLOR_ERROR';
export const TEXT_IMPORTANT = 'TEXT_IMPORTANT';
export const TEXT_INFO = 'TEXT_INFO';
export const TEXT_HELP = 'TEXT_HELP';
export const TEXT_DETAILS = 'TEXT_DETAILS';
export const LIB_TTY = Symbol('tty');
