export const DEFAULT_HEADER_FONT = 'DEFAULT_HEADER_FONT';
export const SECONDARY_HEADER_FONT = 'SECONDARY_HEADER_FONT';
export const OUTPUT_HEADER_FONT = 'OUTPUT_HEADER_FONT';
export const PAGE_SIZE = 'PAGE_SIZE';
export const BLOCK_PRINT_BG = 'BLOCK_PRINT_BG';
export const BLOCK_PRINT_FG = 'BLOCK_PRINT_FG';
export const DISABLE_CLEAR = 'DISABLE_CLEAR';
export const PINNED_ITEMS = 'PINNED_ITEMS';
