export const ICONS = {
  ACTIVATE: '🏁 ',
  CAPTURE: '📷 ',
  COPY: '📋 ',
  CREATE: '➕ ',
  DEBUG: '🐜 ',
  DELETE: '🚫 ',
  DESCRIBE: '🔬 ',
  DESTRUCTIVE: '🚨 ',
  DEVICE: '📟 ',
  DONE: '🗿 ',
  EDIT: '✏ ',
  ENTITIES: '🗃 ',
  GROUPS: '🎳 ',
  LINK: '🔗 ',
  NAME: '💭 ',
  RENAME: '✏ ',
  ROOMS: '🏡 ',
  ROUTINE: '🤖 ',
  STATE_MANAGER: '🎼 ',
};
