import {
  IsDateString,
  IsEnum,
  IsNumber,
  IsObjectId,
  IsOptional,
  validate,
  ValidationError,
} from '@automagical/validation';
import faker from 'faker';
import dayjs from 'dayjs';
import { ACCESS_PERMISSION, AccessTypes } from './constants';
import { Prop } from '@nestjs/mongoose';
import { Schema as MongooseSchema } from 'mongoose';

export class CanFake {
  // #region Public Static Methods

  public static fake(): Record<never, unknown> {
    return {};
  }

  public static validate<T extends Record<never, unknown>>(
    obj: T,
  ): Promise<ValidationError[]> {
    return validate(obj);
  }

  // #endregion Public Static Methods
}

//
export class AccessDTO extends CanFake {
  // #region Public Static Methods

  public static fake(): AccessDTO {
    return {
      ...super.fake(),
      type: faker.random.arrayElement(Object.values(AccessTypes)),
      roles: Array(faker.datatype.number(5)).map(() => faker.random.uuid()),
    };
  }

  // #endregion Public Static Methods

  // #region Object Properties

  @IsEnum(AccessTypes)
  public type: AccessTypes;
  @IsEnum(ACCESS_PERMISSION)
  @IsOptional()
  public permission?: ACCESS_PERMISSION;
  @IsObjectId({
    each: true,
  })
  public roles: string[];

  // #endregion Object Properties
}

export type BaseOmitProps = 'owner' | 'project';
export const timestamps = {
  updatedAt: 'modified',
  createdAt: 'created',
};
/**
 * Common properties between all objects
 */
export abstract class BaseDTO extends CanFake {
  // #region Public Static Methods

  public static fake(): Omit<BaseDTO, BaseOmitProps> {
    return {
      ...super.fake(),
      created: dayjs().toISOString(),
      modified: dayjs().toISOString(),
    };
  }

  // #endregion Public Static Methods

  // #region Object Properties

  /**
   * User ID for owner of this entity
   *
   * See Users collection in Portal Base
   */
  @IsObjectId()
  @IsOptional()
  @Prop({ ref: 'submission', required: true, index: true })
  public owner?: string;
  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
    type: Date,
  })
  public created?: string;
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
    type: Date,
  })
  public modified?: string;
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsObjectId()
  public _id?: string;
  /**
   * If this is defined, then this must be a stage. ID reference to another project
   */
  @IsOptional()
  @IsObjectId()
  @Prop({
    ref: 'project',
    type: MongooseSchema.Types.ObjectId,
    index: true,
    required: true,
    default: null,
  })
  public project?: string;
  @IsOptional()
  @Prop({ default: null })
  @IsNumber()
  public deleted?: number;

  // #endregion Object Properties
}
