export const LUTRON_HOST = 'MQTT_HOST';
export const LUTRON_PORT = 'MQTT_PORT';
export const LUTRON_USERNAME = 'LUTRON_USERNAME';
export const LUTRON_PASSWORD = 'LUTRON_PASSWORD';
export const RECONNECT_INTERVAL = 'RECONNECT_INTERVAL';
