import { TransformObjectId } from '@automagical/persistence';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { IsDateString, IsNumber, IsOptional, IsString } from 'class-validator';
import { Document } from 'mongoose';

export enum LIGHTING_MODE {
  circadian = 'circadian',
  on = 'on',
}
export class PersistenceSwitchStateDTO {
  @Prop({ required: true, type: String })
  entity_id: string;
  @Prop({ enum: ['on', 'off'], required: true, type: String })
  state: 'on' | 'off';
}

export class PersistenceLightStateDTO extends PersistenceSwitchStateDTO {
  @Prop(Number)
  brightness?: number;
  @Prop([Number])
  hs?: [number, number] | number[];
  @Prop(Number)
  kelvin?: number;
  @Prop({
    default: LIGHTING_MODE.on,
    enum: Object.values(LIGHTING_MODE),
    required: true,
  })
  mode: LIGHTING_MODE;
}

@Schema({
  collection: 'room_state',
  minimize: false,
  timestamps: {
    createdAt: 'created',
    updatedAt: 'modified',
  },
})
export class RoomStateDTO<
  STATES extends PersistenceSwitchStateDTO = PersistenceLightStateDTO,
> {
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsString()
  @TransformObjectId()
  public _id?: string;
  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;
  @IsNumber()
  @IsOptional()
  @Prop({ default: null, type: 'number' })
  public deleted?: number;
  @IsString({ each: true })
  @Prop()
  public entities: string[];
  @IsString()
  @Prop()
  public group?: string;
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;
  @IsString()
  @Prop({ required: true, type: String })
  public name: string;
  @IsString()
  @Prop()
  public room: string;
  @Prop({ default: [], required: true })
  public states: STATES[];
}

export type RoomStateDocument = RoomStateDTO & Document;
export const RoomStateSchema = SchemaFactory.createForClass(RoomStateDTO);
RoomStateSchema.index({
  deleted: 1,
  group: 1,
  name: 1,
  room: 1,
});
