export const LUTRON_HOST = 'LUTRON_HOST';
export const LUTRON_PORT = 'LUTRON_PORT';
export const LUTRON_USERNAME = 'LUTRON_USERNAME';
export const LUTRON_PASSWORD = 'LUTRON_PASSWORD';
export const RECONNECT_INTERVAL = 'RECONNECT_INTERVAL';
export const HOMEASSISTANT_URL = 'HOMEASSISTANT_URL';
export const HOMEASSISTANT_TOKEN = 'HOMEASSISTANT_TOKEN';

export const PICO_MAPPINGS = 'PICO_MAPPINGS';
