import { IsDateString, IsOptional, IsString } from '@automagical/validation';
import { Prop } from '@nestjs/mongoose';
import dayjs from 'dayjs';
import { Types } from 'mongoose';

import { CanFake } from './can-fake.dto';

export class DBFake extends CanFake {
  // #region Public Static Methods

  public static fake(): DBFake {
    return {
      _id: Types.ObjectId().toHexString(),
      created: dayjs().toDate(),
      modified: dayjs().toDate(),
    };
  }

  // #endregion Public Static Methods

  // #region Object Properties

  /**
   * Autogenerated creation date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public created?: Date;
  /**
   * Autogenerated last modified date
   */
  @IsOptional()
  @IsDateString()
  @Prop({
    index: true,
  })
  public modified?: Date;
  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsString()
  public _id?: string;

  // #endregion Object Properties
}
