import { IsObjectId, IsOptional } from '@automagical/validation';
import { Types } from 'mongoose';
import { CanFake } from './CanFake.dto';

export class DBFake extends CanFake {
  // #region Public Static Methods

  public static fake(): Record<never, unknown> {
    return {
      _id: Types.ObjectId(),
    };
  }

  // #endregion Public Static Methods

  // #region Object Properties

  /**
   * Autogenerated string
   */
  @IsOptional()
  @IsObjectId()
  public _id?: string;

  // #endregion Object Properties
}
