high:
  all:
    circadian: high
    on:
      - group.games_circadian

medium:
  all:
    circadian: high
    on:
      - group.games_circadian

low:
  all:
    circadian: low
    on:
      - group.games_circadian

off:
  all:
    circadian: off
    off:
      - group.games_circadian

config:
  pico: sensor.games_pico
  temperature: sensor.upstairs_temperature
  fan: fan.games_ceiling_fan
  circadian:
    high: switch.circadian_lighting_games_circadian_light
    low: switch.circadian_lighting_games_low_brightness_circadian_light

groups:
  games_circadian:
    - light.games_1
    - light.games_2
    - light.games_3
    - light.games_lamp
