name: Lint & Test

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - develop
      - master
env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: yarn install
        run: yarn install

      - name: Affected Lint
        shell: bash
        run: npx nx affected --target=lint
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

      - name: Affected Test
        shell: bash
        run: npx nx affected --target=test
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: apps/home-controller/Dockerfile
